version: '3.1'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - todo:/var/lib/mysql
      - ./docker/db/init.d:/docker-entrypoint-initdb.d   # 初期化スクリプトディレクトリをマウント
    networks:
      - todo
    restart: always

  backend:
    image: golang:1.22.5
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo
    tty:
      true
    networks:
      - todo
    restart: always


  frontend:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm install && npm run start
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - todo

volumes:
  todo:

networks:
  todo:
    name: todo
    driver: bridge
    external: true
